server.port=${PORT:8080}

spring.datasource.url=jdbc:mysql://localhost:3307/docchat
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

gemini.api.key=${GEMINI_API_KEY}
gemini.api.embedding-url=https://generativelanguage.googleapis.com/v1beta/models/gemini-embedding-001:embedContent
gemini.api.generate-url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent